name: test-sphinx
on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: jmduarte/sphinx-action@main
      with:
        docs-folder: "docs/"
